name: Hello world

on:
  push:
    branches: -master
  pull_request:
    branches: -master
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hello world
        run: echo "Hello world"'
        shell: bash
